-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 21:52:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hiraoka
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hiraoka
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hiraoka` DEFAULT CHARACTER SET utf8 ;
USE `hiraoka` ;

-- -----------------------------------------------------
-- Table `hiraoka`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiraoka`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '				';


-- -----------------------------------------------------
-- Table `hiraoka`.`celulares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiraoka`.`celulares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_id` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `codigo` VARCHAR(6) NOT NULL,
  `stock` VARCHAR(4) NOT NULL,
  `precio_online` DECIMAL(5,2) NULL,
  `precio_normal` DECIMAL(5,2) NOT NULL,
  `imagen` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_celulares_marcas_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `fk_celulares_marcas`
    FOREIGN KEY (`marca_id`)
    REFERENCES `hiraoka`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiraoka`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiraoka`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` TEXT NULL,
  `email` VARCHAR(320) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiraoka`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiraoka`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `estado` TINYINT NULL,
  `monto_total` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_usuarios1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `hiraoka`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hiraoka`.`detalle_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hiraoka`.`detalle_pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedido_id` INT NOT NULL,
  `celular_id` INT NOT NULL,
  `cantidad` TINYINT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_pedidos_pedidos1_idx` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_detalle_pedidos_celulares1_idx` (`celular_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_pedidos_pedidos1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `hiraoka`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_pedidos_celulares1`
    FOREIGN KEY (`celular_id`)
    REFERENCES `hiraoka`.`celulares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
