"""crear tabla usuarios

Revision ID: 08041ee7f496
Revises: 
Create Date: 2022-10-11 20:20:08.157267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08041ee7f496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=45), nullable=False),
    sa.Column('apellidos', sa.String(length=45), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('usuario_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
