"""agregar columna passwordSalt

Revision ID: 1e07cbc1062a
Revises: a5a03f245ad7
Create Date: 2022-10-12 15:04:38.140548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e07cbc1062a'
down_revision = 'a5a03f245ad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_salt', sa.String(length=60), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'password_salt')
    # ### end Alembic commands ###
