"""Added celular.estado

Revision ID: 26e6b853b4bd
Revises: 54e98aa8199b
Create Date: 2022-10-19 11:06:21.145861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e6b853b4bd'
down_revision = '54e98aa8199b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celulares', sa.Column('estado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celulares', 'estado')
    # ### end Alembic commands ###
