"""agregar columna celulares.stock

Revision ID: 54e98aa8199b
Revises: 1e07cbc1062a
Create Date: 2022-10-12 18:42:11.024277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e98aa8199b'
down_revision = '1e07cbc1062a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celulares', sa.Column('stock', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celulares', 'stock')
    # ### end Alembic commands ###
