"""crear tabla celulares

Revision ID: 578398be31c3
Revises: b431d11ce031
Create Date: 2022-10-12 10:20:06.857173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '578398be31c3'
down_revision = 'b431d11ce031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celulares',
    sa.Column('celular_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('codigo', sa.String(length=6), nullable=True),
    sa.Column('precio_online', sa.Float(precision=5, asdecimal=2), nullable=True),
    sa.Column('precio_normal', sa.Float(precision=5, asdecimal=2), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marca_id'], ['marcas.marca_id'], ),
    sa.PrimaryKeyConstraint('celular_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celulares')
    # ### end Alembic commands ###
