"""crear tabla detalle_pedidos

Revision ID: a5a03f245ad7
Revises: 578398be31c3
Create Date: 2022-10-12 10:21:02.102609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5a03f245ad7'
down_revision = '578398be31c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_pedidos',
    sa.Column('detalle_pedido_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('celular_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', mysql.TINYINT(), nullable=True),
    sa.Column('precio', sa.Float(precision=5, asdecimal=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['celular_id'], ['celulares.celular_id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.pedido_id'], ),
    sa.PrimaryKeyConstraint('detalle_pedido_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_pedidos')
    # ### end Alembic commands ###
