"""crear tabla marcas

Revision ID: b431d11ce031
Revises: 845a2d7d758c
Create Date: 2022-10-12 10:18:46.984981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b431d11ce031'
down_revision = '845a2d7d758c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('marca_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marcas')
    # ### end Alembic commands ###
